language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script: ./mvnw clean package -Pprod -B -V

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      cp src/main/docker/* target/;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -t "guggero/aare-api:latest" target/;
      docker build -t "guggero/aare-api:$TRAVIS_BUILD_NUMBER" target/;
      docker push "guggero/aare-api:latest";
      docker push "guggero/aare-api:$TRAVIS_BUILD_NUMBER";
    fi
