sudo: required
language: java

dist: trusty

services:
 - docker

cache:
  directories:
    - $HOME/.m2

script: mvn clean package -B -V

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -t "guggero/aare-server:latest" docker/;
      docker build -t "guggero/aare-server:$TRAVIS_BUILD_NUMBER" docker/;
      docker push "guggero/aare-server:latest";
      docker push "guggero/aare-server:$TRAVIS_BUILD_NUMBER";
    fi